from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AbstractNotificationMessage(BaseModel):
    type: str | None = None