from pydantic import BaseModel

from .id import Id

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AlarmAssetLink(BaseModel):
    id: Id | None = None
    createdOn: str | None = None
    assetName: str | None = None
    parentAssetName: str | None = None