from typing import Literal
from pydantic import BaseModel

from .parent_predicate import ParentPredicate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetConditions(BaseModel):
    access: list[Literal['RESTRICTED', 'LINKED', 'REALM']] | None = None
    minAmount: Literal['AT_LEAST_ONE', 'ALL', 'NONE'] | None = None
    parents: list[ParentPredicate] | None = None