from typing import Literal
from pydantic import BaseModel

from .select import Select
from .string_predicate import StringPredicate
from .parent_predicate import ParentPredicate
from .path_predicate import PathPredicate
from .realm_predicate import RealmPredicate
from .logic_group_attribute_predicate import LogicGroupAttributePredicate
from .order_by import OrderBy

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetQuery(BaseModel):
    recursive: bool | None = None
    select: Select | None = None
    access: Literal['PRIVATE', 'PROTECTED', 'PUBLIC'] | None = None
    ids: list[str] | None = None
    names: list[StringPredicate] | None = None
    parents: list[ParentPredicate] | None = None
    paths: list[PathPredicate] | None = None
    realm: RealmPredicate | None = None
    userIds: list[str] | None = None
    types: list[str] | None = None
    attributes: LogicGroupAttributePredicate | None = None
    orderBy: OrderBy | None = None
    limit: int | None = None
    offset: int | None = None