from pydantic import BaseModel

from .asset_tree_asset import AssetTreeAsset

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetTree(BaseModel):
    assets: list[AssetTreeAsset] | None = None
    hasMore: bool | None = None