from pydantic import BaseModel

from .asset_descriptor_object import AssetDescriptorObject
from .attribute_descriptor_object import AttributeDescriptorObject
from .meta_item_descriptor_object import MetaItemDescriptorObject
from .value_descriptor_object import ValueDescriptorObject

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetTypeInfo(BaseModel):
    assetDescriptor: AssetDescriptorObject | None = None
    attributeDescriptors: list[AttributeDescriptorObject] | None = None
    metaItemDescriptors: list[MetaItemDescriptorObject] | None = None
    valueDescriptors: list[ValueDescriptorObject] | None = None