from pydantic import BaseModel

from .asset_object import AssetObject
from .asset_tree_node import AssetTreeNode

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetTreeNode(BaseModel):
    asset: AssetObject | None = None
    children: list[AssetTreeNode] | None = None