from typing import Any
from pydantic import BaseModel

from .value_descriptor_object import ValueDescriptorObject
from .value_constraint import ValueConstraint
from .value_format import ValueFormat

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributeDescriptorObject(BaseModel):
    name: str | None = None
    type: ValueDescriptorObject | None = None
    constraints: list[ValueConstraint] | None = None
    format: ValueFormat | None = None
    units: list[str] | None = None
    meta: dict[Any, Any] | None = None
    optional: bool | None = None