from typing import Any
from pydantic import BaseModel

from .string_predicate import StringPredicate
from .value_predicate import ValuePredicate
from .name_value_predicate import NameValuePredicate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributePredicate(BaseModel):
    name: StringPredicate | None = None
    negated: bool | None = None
    path: list[dict[Any, Any]] | None = None
    value: ValuePredicate | None = None
    meta: list[NameValuePredicate] | None = None
    previousValue: ValuePredicate | None = None
    timestampOlderThan: str | None = None