from typing import Any
from pydantic import BaseModel

from .attribute_state import AttributeState
from .attribute_ref import AttributeRef
from .value_descriptor import ValueDescriptor

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributeEvent(BaseModel):
    attributeState: AttributeState | None = None
    ref: AttributeRef | None = None
    value: dict[Any, Any] | None = None
    timestamp: int | None = None
    messageID: str | None = None
    deleted: bool | None = None
    realm: str | None = None
    parentId: str | None = None
    oldValue: dict[Any, Any] | None = None
    oldValueTimestamp: int | None = None
    path: list[str] | None = None
    assetName: str | None = None
    assetType: str | None = None
    createdOn: str | None = None
    type: ValueDescriptor | None = None