from typing import Any
from pydantic import BaseModel

from .value_descriptor_object import ValueDescriptorObject

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributeObject(BaseModel):
    type: ValueDescriptorObject | None = None
    value: dict[Any, Any] | None = None
    name: str
    meta: dict[Any, Any] | None = None
    timestamp: int | None = None