from typing import Any
from pydantic import BaseModel

from .attribute_ref import AttributeRef

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributeState(BaseModel):
    ref: AttributeRef | None = None
    value: dict[Any, Any] | None = None