from pydantic import BaseModel

from .string_predicate import StringPredicate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributeValuePredicate(BaseModel):
    negated: bool | None = None
    name: StringPredicate | None = None
    value: StringPredicate | None = None