from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AttributeRef(BaseModel):
    id: str | None = None
    name: str