from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class BooleanPredicate(BaseModel):
    predicateType: str
    value: bool | None = None