from pydantic import BaseModel

from .dashboard_conditions import DashboardConditions
from .asset_conditions import AssetConditions

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Conditions(BaseModel):
    dashboard: DashboardConditions | None = None
    asset: AssetConditions | None = None