from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Credential(BaseModel):
    type: str | None = None
    value: str | None = None
    temporary: bool | None = None