from typing import Any
from pydantic import BaseModel

from .dashboard_grid_item import DashboardGridItem

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class DashboardWidget(BaseModel):
    id: str | None = None
    displayName: str
    gridItem: DashboardGridItem
    widgetTypeId: str
    widgetConfig: dict[Any, Any] | None = None