from typing import Literal
from pydantic import BaseModel

from .dashboard_template import DashboardTemplate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Dashboard(BaseModel):
    id: str | None = None
    createdOn: str | None = None
    realm: str
    version: int | None = None
    ownerId: str | None = None
    access: Literal['PUBLIC', 'SHARED', 'PRIVATE'] | None = None
    displayName: str
    template: DashboardTemplate