from typing import Literal
from pydantic import BaseModel

from .dashboard_screen_preset import DashboardScreenPreset
from .dashboard_widget import DashboardWidget

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class DashboardTemplate(BaseModel):
    id: str | None = None
    columns: int | None = None
    maxScreenWidth: int | None = None
    refreshInterval: Literal['OFF', 'ONE_MIN', 'FIVE_MIN', 'QUARTER', 'ONE_HOUR'] | None = None
    screenPresets: list[DashboardScreenPreset]
    widgets: list[DashboardWidget] | None = None