from pydantic import BaseModel

from .select import Select
from .conditions import Conditions
from .string_predicate import StringPredicate
from .realm_predicate import RealmPredicate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class DashboardQuery(BaseModel):
    select: Select | None = None
    conditions: Conditions | None = None
    ids: list[str] | None = None
    names: list[StringPredicate] | None = None
    userIds: list[str] | None = None
    realm: RealmPredicate | None = None
    start: int | None = None
    limit: int | None = None