from typing import Literal
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class DashboardConditions(BaseModel):
    access: list[Literal['PUBLIC', 'SHARED', 'PRIVATE']] | None = None