from pydantic import BaseModel

from .recipient import Recipient

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class EmailNotificationMessage(BaseModel):
    type: str | None = None
    from: Recipient | None = None
    replyTo: Recipient | None = None
    subject: str | None = None
    text: str | None = None
    html: str | None = None
    to: list[Recipient] | None = None
    cc: list[Recipient] | None = None
    bcc: list[Recipient] | None = None