from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class FileInfo(BaseModel):
    name: str | None = None
    contents: str | None = None
    binary: bool | None = None