from typing import Any
from pydantic import BaseModel

from .asset_query import AssetQuery

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class GatewayAttributeFilter(BaseModel):
    matcher: AssetQuery | None = None
    duration: str | None = None
    delta: Any | None = None
    valueChange: bool | None = None
    skipAlways: bool | None = None
    durationParsedMillis: int | None = None