from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Id(BaseModel):
    realm: str | None = None
    userId: str | None = None
    assetId: str | None = None