from typing import Literal
from pydantic import BaseModel

from .attribute_predicate import AttributePredicate
from .logic_group_attribute_predicate import LogicGroupAttributePredicate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class LogicGroupAttributePredicate(BaseModel):
    operator: Literal['AND', 'OR'] | None = None
    items: list[AttributePredicate] | None = None
    groups: list[LogicGroupAttributePredicate] | None = None