from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class ManagerAppRealmNotificationConfig(BaseModel):
    languages: list[str] | None = None
    defaultLanguage: str | None = None