from typing import Any
from pydantic import BaseModel

from .manager_config import ManagerConfig

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class ManagerAppConfig(BaseModel):
    loadLocales: bool | None = None
    languages: dict[Any, Any] | None = None
    realms: dict[Any, Any] | None = None
    pages: dict[Any, Any] | None = None
    manager: ManagerConfig | None = None