from typing import Any
from pydantic import BaseModel

from .geo_json_config import GeoJsonConfig

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class MapRealmConfig(BaseModel):
    center: list[Any] | None = None
    bounds: list[Any] | None = None
    zoom: int | None = None
    minZoom: int | None = None
    maxZoom: int | None = None
    boxZoom: bool | None = None
    geocodeUrl: str | None = None
    geoJson: GeoJsonConfig | None = None