from typing import Any
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class MetaMap(BaseModel):
    delegate: dict[Any, Any] | None = None