from typing import Any
from pydantic import BaseModel

from .string_predicate import StringPredicate
from .value_predicate import ValuePredicate

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class NameValuePredicate(BaseModel):
    name: StringPredicate | None = None
    negated: bool | None = None
    path: list[dict[Any, Any]] | None = None
    value: ValuePredicate | None = None