from typing import Literal
from pydantic import BaseModel

from .node_position import NodePosition
from .node_internal import NodeInternal
from .node_socket import NodeSocket

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Node(BaseModel):
    id: str | None = None
    type: Literal['INPUT', 'PROCESSOR', 'OUTPUT', 'THEN'] | None = None
    priority: int | None = None
    name: str | None = None
    position: NodePosition | None = None
    size: NodePosition | None = None
    internals: list[NodeInternal] | None = None
    inputs: list[NodeSocket] | None = None
    outputs: list[NodeSocket] | None = None
    displayCharacter: str | None = None