from typing import Any
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class NodePosition(BaseModel):
    x: Any | None = None
    y: Any | None = None