from typing import Any
from typing import Literal
from pydantic import BaseModel

from .picker import Picker

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class NodeInternal(BaseModel):
    name: str | None = None
    picker: Picker | None = None
    value: dict[Any, Any] | None = None
    breakType: Literal['NEW_LINE', 'SPACER'] | None = None