from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class NotNull(BaseModel):
    message: str | None = None
    type: str