from typing import Literal
from pydantic import BaseModel

from .abstract_notification_message import AbstractNotificationMessage
from .target import Target

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Notification(BaseModel):
    name: str | None = None
    message: AbstractNotificationMessage | None = None
    targets: list[Target] | None = None
    repeatFrequency: Literal['ALWAYS', 'ONCE', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'ANNUALLY'] | None = None
    repeatInterval: str | None = None