from typing import Any
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Option(BaseModel):
    name: str | None = None
    value: dict[Any, Any] | None = None