from typing import Literal
from pydantic import BaseModel

from .option import Option

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Picker(BaseModel):
    type: Literal['TEXT', 'MULTILINE', 'NUMBER', 'DROPDOWN', 'DOUBLE_DROPDOWN', 'CHECKBOX', 'ASSET_ATTRIBUTE', 'COLOR', 'DATE'] | None = None
    options: list[Option] | None = None