from typing import Any
from typing import Literal
from pydantic import BaseModel

from .push_notification_action import PushNotificationAction
from .push_notification_button import PushNotificationButton

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class PushNotificationMessage(BaseModel):
    type: str | None = None
    title: str | None = None
    body: str | None = None
    action: PushNotificationAction | None = None
    buttons: list[PushNotificationButton] | None = None
    data: dict[Any, Any] | None = None
    priority: Literal['NORMAL', 'HIGH'] | None = None
    targetType: Literal['DEVICE', 'TOPIC', 'CONDITION'] | None = None
    target: str | None = None
    expiration: int | None = None