from pydantic import BaseModel

from .push_notification_action import PushNotificationAction

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class PushNotificationButton(BaseModel):
    title: str | None = None
    action: PushNotificationAction | None = None