from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class RealmRole(BaseModel):
    name: str | None = None
    description: str | None = None