from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class RealmPredicate(BaseModel):
    name: str | None = None