from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Recipient(BaseModel):
    name: str | None = None
    address: str | None = None