from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Select(BaseModel):
    basic: bool | None = None