from typing import Literal
from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class StringPredicate(BaseModel):
    match: Literal['EXACT', 'BEGIN', 'END', 'CONTAINS'] | None = None
    caseSensitive: bool | None = None
    value: str | None = None
    negate: bool | None = None