from pydantic import BaseModel

from .realm_predicate import RealmPredicate
from .path_predicate import PathPredicate
from .select import Select
from .string_predicate import StringPredicate
from .attribute_value_predicate import AttributeValuePredicate
from .order_by import OrderBy

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class UserQuery(BaseModel):
    realmPredicate: RealmPredicate | None = None
    assets: list[str] | None = None
    pathPredicate: PathPredicate | None = None
    ids: list[str] | None = None
    select: Select | None = None
    usernames: list[StringPredicate] | None = None
    attributes: list[AttributeValuePredicate] | None = None
    clientRoles: list[StringPredicate] | None = None
    realmRoles: list[StringPredicate] | None = None
    serviceUsers: bool | None = None
    limit: int | None = None
    offset: int | None = None
    orderBy: OrderBy | None = None