from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class UsernamePassword(BaseModel):
    username: str | None = None
    password: str | None = None