from pydantic import BaseModel

from .value_constraint import ValueConstraint
from .value_format import ValueFormat

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class ValueDescriptor(BaseModel):
    name: str | None = None
    constraints: list[ValueConstraint] | None = None
    format: ValueFormat | None = None
    units: list[str] | None = None
    arrayDimensions: int | None = None
    metaUseOnly: bool | None = None
    jsonType: str | None = None