from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class ValueEmptyPredicate(BaseModel):
    predicateType: str
    negate: bool | None = None