from pydantic import BaseModel


################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class X509ProvisioningData(BaseModel):
    CACertPEM: str | None = None
    ignoreExpiryDate: bool | None = None