from utils import convert_camel_case_to_snake_case, convert_to_camel_case


def generate_api(paths: dict[str, dict]):
    files = {}
    tags = {}

    # Sort path/methods based on their tags
    for path, endpoints in paths.items():
        for method, endpoint_data in endpoints.items():
            tag_name = endpoint_data.get("tags")[0] or "__default"

            if tag_name not in tags:
                tags[tag_name] = []

            endpoint_data["path"] = path
            endpoint_data["method"] = method

            tags[tag_name].append(endpoint_data)

    for tag, endpoints in tags.items():
        files[tag] = create_new_class(tag, endpoints)

    return files


def create_new_class(tag: str, endpoints: dict):
    file_lines = [
        "from httpx import Response",
        "",
        "from ..http import HttpClient"
    ]


    file_lines.extend([
        "",
        "################################################################",
        "# This file is auto-generated by the openapi_generator script. #",
        "################################################################",
        "",
        ""
    ])

    file_lines.extend([
        f"class {convert_to_camel_case(tag)}:",
        "    __client: HttpClient",
        "",
        "    def __init__(self, client: HttpClient):",
        "        self.__client = client",
        ""
    ])

    for endpoint in endpoints:
        file_lines.extend(parse_endpoint(endpoint))

    return '\n'.join(file_lines)


def parse_endpoint(endpoint: dict):

    endpoint_name = endpoint.get('operationId')
    endpoint_method = endpoint.get('method')
    endpoint_path = endpoint.get('path')
    endpoint_description = endpoint.get('summary')

    # Function start
    lines = [
        f"    async def {convert_camel_case_to_snake_case(endpoint_name)}(self) -> Response:"
    ]

    # Description start
    lines.extend([
        f'        """',
        f'        {endpoint_description}',
        "",
    ])

    responses_lines = [
        "        Possible responses:",
    ]

    for status_code, response in endpoint.get('responses').items():
        responses_lines.extend([
            "",
            f"        {status_code} - {response.get('description')}",
            ""
        ])

    lines.extend(responses_lines)

    # Description end
    lines.extend([
        f'        """',
    ])

    # Function code
    lines.extend([
        f"        return await self.__client.{endpoint_method}('{endpoint_path}')",
        ""
    ])

    return lines