from utils import convert_camel_case_to_snake_case, convert_to_camel_case, resolve_type


def generate_api(paths: dict[str, dict]):
    files = {}
    tags = {}

    # Sort path/methods based on their tags
    for path, endpoints in paths.items():
        for method, endpoint_data in endpoints.items():
            tag_name = endpoint_data.get("tags")[0] or "__default"

            if tag_name not in tags:
                tags[tag_name] = []

            endpoint_data["path"] = path
            endpoint_data["method"] = method

            tags[tag_name].append(endpoint_data)

    for tag, endpoints in tags.items():
        files[tag] = create_new_class(tag, endpoints)

    return files


def create_new_class(tag: str, endpoints: dict):
    file_lines = [
        "from ..response import ResponseModel",
        "",
        "from typing import Any, Literal",
        "from ..http import HttpClient",
        "from httpx._types import HeaderTypes",
        ""
    ]

    imports = set()

    for endpoint in endpoints:
        return_class = endpoint_resolve_return(endpoint)
        request_body = endpoint_resolve_request_body(endpoint)

        if return_class not in ['None', 'Any', 'list', 'dict', 'Literal', 'str', 'int', 'float', 'bool']:
            imports.add(return_class)

        if request_body not in [None, 'None', 'Any', 'list', 'dict', 'Literal', 'str', 'int', 'float', 'bool']:
            imports.add(request_body)

    for import_stmt in imports:
        file_lines.append(f"from ..schemas.{convert_camel_case_to_snake_case(import_stmt).removesuffix('_schema')} import {import_stmt}")


    file_lines.extend([
        "",
        "################################################################",
        "# This file is auto-generated by the openapi_generator script. #",
        "################################################################",
        "",
        ""
    ])

    file_lines.extend([
        f"class {convert_to_camel_case(tag)}:",
        "    __client: HttpClient",
        "",
        "    def __init__(self, client: HttpClient):",
        "        self.__client = client",
        ""
    ])

    for endpoint in endpoints:
        file_lines.extend(parse_endpoint(endpoint))

    return '\n'.join(file_lines)


def endpoint_resolve_request_body(endpoint: dict) -> str | None:
    if 'requestBody' in endpoint.keys():
        if "application/json" in endpoint.get('requestBody').get('content').keys():
            return resolve_type(endpoint.get('requestBody').get('content').get('application/json').get('schema'))

    return None


def endpoint_resolve_return(endpoint: dict) -> str:
    output = 'Any'

    for status_code, response in endpoint.get('responses').items():
        if status_code == '204':
            output = "None"
            break

        if status_code.startswith('2') and 'application/json' in response.get('content').keys():
            schema = response.get('content').get('application/json').get('schema')

            if not schema:
                output = "None"
                break

            if '$ref' in schema.keys():
                output = schema.get('$ref').split('/')[-1]
                break
            elif 'type' in schema.keys():
                match schema.get('type'):
                    case "array":
                        output = "list"
                        break
                    case "object":
                        output = "dict"
                        break

    if output not in ['None', 'Any', 'int', 'str', 'bool', 'list', 'dict', 'Literal', 'float']:
        output += "Schema"

    return output


def parse_endpoint(endpoint: dict):

    endpoint_name = endpoint.get('operationId')
    endpoint_method = endpoint.get('method')
    endpoint_path = endpoint.get('path')
    endpoint_description = endpoint.get('summary')

    endpoint_return = endpoint_resolve_return(endpoint)

    parameters = endpoint.get('parameters')
    path_parameters = []

    request_body = endpoint_resolve_request_body(endpoint)

    if parameters:
        for parameter in parameters:
            if parameter.get('in') == 'path':
                path_parameters.append(parameter)

    def resolve_function_parameters() -> str:
        params = ['self']

        # Resolve path parameters first
        for path_parameter in path_parameters:
            param = ''

            match path_parameter.get('schema').get('type'):
                case "string":
                    param = f"{convert_camel_case_to_snake_case(path_parameter.get('name'))}: str"
                case "integer":
                    param = f"{convert_camel_case_to_snake_case(path_parameter.get('name'))}: int"
                case "float":
                    param = f"{convert_camel_case_to_snake_case(path_parameter.get('name'))}: float"
                case "bool":
                    param = f"{convert_camel_case_to_snake_case(path_parameter.get('name'))}: bool"
                case _:
                    param = f"{convert_camel_case_to_snake_case(path_parameter.get('name'))}: Any"

            if not path_parameter.get('required'):
                param += f"{param} | None = None"

            params.append(param)

        if request_body:
            params.append(f"{convert_camel_case_to_snake_case(request_body)}: {request_body}")


        params.append('headers: HeaderTypes | None = None')

        return ', '.join(params)

    # Function start
    lines = [
        f"    async def {convert_camel_case_to_snake_case(endpoint_name)}({resolve_function_parameters()}) -> ResponseModel[{endpoint_return}]:"
    ]

    # Description start
    lines.extend([
        f'        """',
        f'        {endpoint_description}',
        "",
    ])

    responses_lines = [
        "        Possible responses:",
    ]

    for status_code, response in endpoint.get('responses').items():
        responses_lines.extend([
            "",
            f"          {status_code} - {response.get('description')}",
            f"          {response.get('content')}",
            ""
        ])

    lines.extend(responses_lines)

    # Description end
    lines.extend([
        f'        """',
    ])

    request_body_line = ""

    if request_body is not None:
        if request_body.endswith('Schema'):
            request_body_line = f"            json={convert_camel_case_to_snake_case(request_body)}.model_dump(),\n"

    # Function code
    lines.extend([
        f"        response = await self.__client.{endpoint_method}(",
        f"            path={'f' if path_parameters else ''}'{convert_camel_case_to_snake_case(endpoint_path)}',",
        f"{request_body_line}            headers=headers",
        f"        )",
        "",
        "        response.raise_for_status()",
        "",
        "        return ResponseModel(",
        "            status_code=response.status_code,",
        f"            content={endpoint_return}{'(**response.json())' if endpoint_return not in ['None', 'Any'] else ''},",
        "            response=response",
        "        )",
        ""
    ])

    return lines