from typing import Any, Dict, List
from utils import convert_to_snake_case

def get_import(prop_schema: Dict[str, Any]) -> str | None:
    if prop_schema.get('$ref'):
        return prop_schema['$ref'].split('/')[-1]

    match prop_schema.get('type'):
        case "array":
            array_schema = prop_schema["items"]
            if array_schema.get('$ref'):
                return array_schema['$ref'].split('/')[-1]

    return None


def get_prop_type(prop_schema: Dict[str, Any]) -> str:
    if prop_schema.get('$ref'):
        return prop_schema['$ref'].split('/')[-1]

    match prop_schema.get('type'):
        case "string":
            if prop_schema.get('enum'):
                return f"Literal[{', '.join(map(repr, prop_schema['enum']))}]"

            return "str"
        case "integer":
            return "int"
        case "boolean":
            return "bool"
        case "float":
            return "float"
        case "object":
            return "dict[Any, Any]"
        case "array":
            if list_type := get_prop_type(prop_schema["items"]):
                return f"list[{list_type}]"

            return "list"
        case _:
            return "Any"

def parse_property(prop_name: str, prop_schema: Dict[str, Any], required_props: List[str] = None):
    if required_props is None:
        required_props = []

    prop_type = get_prop_type(prop_schema)

    output = f"{prop_name}: {prop_type}"

    if prop_name not in required_props:
        output += " | None = None"

    return f"    {output}"


def parse_schemas_properties(name: str, schemas: Dict[str, Any]) -> list[str]:
    """
    Convert a single schema into a Pydantic model definition.
    Supports simple object types and $ref resolution.
    """
    # Handle composition via allOf
    lines = []

    schema = schemas[name]

    if "allOf" in schema:
        for part in schema["allOf"]:
            if "$ref" in part:
                ref_name = part["$ref"].split("/")[-1]
                lines.extend(parse_schemas_properties(ref_name, schemas))
            elif "properties" in part:
                for prop, prop_schema in part["properties"].items():
                    lines.append(parse_property(prop, prop_schema, schema.get("required")))

    # Handle regular object schema
    if schema.get("type") == "object" and "properties" in schema:
        for prop, prop_schema in schema["properties"].items():
            lines.append(parse_property(prop, prop_schema, schema.get("required")))

    if not lines:
        lines.append('    pass')

    return lines


def parse_schemas_imports(name: str, schemas: Dict[str, Any]) -> list[str]:
    """
    Convert a single schema into a Pydantic model definition.
    Supports simple object types and $ref resolution.
    """
    # Handle composition via allOf
    imports = []

    schema = schemas[name]

    if "allOf" in schema:
        for part in schema["allOf"]:
            if "properties" in part:
                for prop, prop_schema in part["properties"].items():
                    import_name = get_import(prop_schema)

                    if import_name is not None and import_name not in imports:
                        imports.append(import_name)

    # Handle regular object schema
    if schema.get("type") == "object" and "properties" in schema:
        for prop, prop_schema in schema["properties"].items():
            import_name = get_import(prop_schema)

            if import_name is not None and import_name not in imports:
                imports.append(import_name)

    return imports


def generate_pydantic_models(components: Dict[str, Any]) -> dict[str, str]:
    """Generate Pydantic models for all schemas in components."""

    files = {}

    for name, schema in components.items():
        file_content = parse_schemas_properties(name, components)
        file_content_raw = '\n'.join(file_content)
        file_imports = parse_schemas_imports(name, components)

        file_lines = []

        for import_name in ['Any', 'List', 'Dict', 'Literal']:
            include_imports = []

            if import_name in file_content_raw:
                include_imports.append(import_name)

            if include_imports:
                file_lines.append(f"from typing import {', '.join(include_imports)}")

        file_lines.extend([
            ""
            "from pydantic import BaseModel",
            ""
        ])

        for import_name in file_imports:
            file_lines.append(f"from .{convert_to_snake_case(import_name)} import {import_name}")


        file_lines.extend([
            "",
            "################################################################",
            "# This file is auto-generated by the openapi_generator script. #",
            "################################################################",
            "",
            ""
        ])

        file_lines.append(f"class {name}(BaseModel):")
        file_lines.extend(file_content)
        files[name] = '\n'.join(file_lines)

    return files
