from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Agent:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def do_protocol_asset_discovery(self, agent_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Do protocol asset discovery

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/AssetTreeNode'}}}}

        """
        response = await self.__client.get(
            path=f'/agent/asset_discovery/{agent_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def do_protocol_asset_import(self, agent_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Do protocol asset import

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/AssetTreeNode'}}}}

        """
        response = await self.__client.post(
            path=f'/agent/asset_import/{agent_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def do_protocol_instance_discovery(self, agent_type = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Do protocol instance discovery

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/AgentObjectObjectObject'}}}}

        """
        response = await self.__client.get(
            path=f'/agent/instance_discovery/{agent_type}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )
