from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetPredictedDatapoint:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def write_predicted_datapoints(self, asset_id = str, attribute_name = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Write the predicted datapoints of an asset attribute

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/asset/predicted/{asset_id}/{attribute_name}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_predicted_datapoints(self, asset_id = str, attribute_name = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve the predicted datapoints of an asset attribute

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/ValueDatapointObject'}}}}

        """
        response = await self.__client.post(
            path=f'/asset/predicted/{asset_id}/{attribute_name}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )
