from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class AssetDatapoint:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def get_datapoint_export(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Retrieve a datapoint export of an asset attribute

        Possible responses:

          200 - default response
          {'application/zip': {}}

        """
        response = await self.__client.get(
            path='/asset/datapoint/export',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_datapoint_period(self, headers: HeaderTypes | None = None) -> ResponseModel[DatapointPeriod]:
        """
        Retrieve a datapoint period of an asset attribute

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/DatapointPeriod'}}}

        """
        response = await self.__client.get(
            path='/asset/datapoint/periods',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=DatapointPeriod(**response.json()),
            response=response
        )

    async def get_datapoints(self, asset_id = str, attribute_name = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve the historical datapoints of an asset attribute

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/ValueDatapointObject'}}}}

        """
        response = await self.__client.post(
            path=f'/asset/datapoint/{asset_id}/{attribute_name}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )
