from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Configuration:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def file_upload(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Upload a file

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'string'}}}

        """
        response = await self.__client.post(
            path='/configuration/manager/file',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_manager_config(self, headers: HeaderTypes | None = None) -> ResponseModel[ManagerAppConfig]:
        """
        Retrieve the manager configuration JSON

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ManagerAppConfig'}}}

        """
        response = await self.__client.get(
            path='/configuration/manager',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ManagerAppConfig(**response.json()),
            response=response
        )

    async def update_configuration(self, headers: HeaderTypes | None = None) -> ResponseModel[ManagerAppConfig]:
        """
        Update manager configuration

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ManagerAppConfig'}}}

        """
        response = await self.__client.put(
            path='/configuration/manager',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ManagerAppConfig(**response.json()),
            response=response
        )

    async def get_manager_config_image(self, filename = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Retrieve manager configuration images

        Possible responses:

          200 - default response
          {'*/*': {'schema': {'type': 'object'}}}

        """
        response = await self.__client.get(
            path=f'/configuration/manager/image/{filename}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )
