from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Console:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def register(self, headers: HeaderTypes | None = None) -> ResponseModel[ConsoleRegistration]:
        """
        Create or update the registration for a console

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ConsoleRegistration'}}}

        """
        response = await self.__client.post(
            path='/console/register',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ConsoleRegistration(**response.json()),
            response=response
        )
