from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Dashboard:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def update_dashboard(self, headers: HeaderTypes | None = None) -> ResponseModel[Dashboard]:
        """
        Update a dashboard

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/Dashboard'}}}

        """
        response = await self.__client.put(
            path='/dashboard',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Dashboard(**response.json()),
            response=response
        )

    async def create_dashboard(self, headers: HeaderTypes | None = None) -> ResponseModel[Dashboard]:
        """
        Create a dashboard

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/Dashboard'}}}

        """
        response = await self.__client.post(
            path='/dashboard',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Dashboard(**response.json()),
            response=response
        )

    async def get_dashboard(self, realm = str, dashboard_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Dashboard]:
        """
        Retrieve a dashboard

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/Dashboard'}}}

        """
        response = await self.__client.get(
            path=f'/dashboard/{realm}/{dashboard_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Dashboard(**response.json()),
            response=response
        )

    async def delete_dashboard(self, realm = str, dashboard_id = str, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Delete a dashboard

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.delete(
            path=f'/dashboard/{realm}/{dashboard_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def get_all_realm_dashboards(self, realm = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve all accessible dashboards

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Dashboard'}}}}

        """
        response = await self.__client.get(
            path=f'/dashboard/all/{realm}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def query_dashboards(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve dashboards using a query

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Dashboard'}}}}

        """
        response = await self.__client.post(
            path='/dashboard/query',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )
