from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Map:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def delete_map(self, headers: HeaderTypes | None = None) -> ResponseModel[ObjectNode]:
        """
        Removes mbtiles file

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ObjectNode'}}}

        """
        response = await self.__client.delete(
            path='/map/delete_map',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ObjectNode(**response.json()),
            response=response
        )

    async def get_custom_map_info(self, headers: HeaderTypes | None = None) -> ResponseModel[ObjectNode]:
        """
        Retrieve if the map is custom and custom map limit

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ObjectNode'}}}

        """
        response = await self.__client.get(
            path='/map/get_custom_map_info',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ObjectNode(**response.json()),
            response=response
        )

    async def get_settings(self, headers: HeaderTypes | None = None) -> ResponseModel[ObjectNode]:
        """
        Retrieve the style used for Mapbox GL

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ObjectNode'}}}

        """
        response = await self.__client.get(
            path='/map',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ObjectNode(**response.json()),
            response=response
        )

    async def save_settings(self, headers: HeaderTypes | None = None) -> ResponseModel[ObjectNode]:
        """
        Update map settings

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ObjectNode'}}}

        """
        response = await self.__client.put(
            path='/map',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ObjectNode(**response.json()),
            response=response
        )

    async def get_settings_js(self, headers: HeaderTypes | None = None) -> ResponseModel[ObjectNode]:
        """
        Retrieve the tileJSON object used for Mapbox GL

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ObjectNode'}}}

        """
        response = await self.__client.get(
            path='/map/js',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ObjectNode(**response.json()),
            response=response
        )

    async def get_tile(self, zoom = int, column = int, row = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Retrieve the vector tile data for Mapbox GL

        Possible responses:

          200 - default response
          {'application/vnd.mapbox-vector-tile': {'schema': {'type': 'string', 'format': 'byte'}}}

        """
        response = await self.__client.get(
            path=f'/map/tile/{zoom}/{column}/{row}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def upload_map(self, headers: HeaderTypes | None = None) -> ResponseModel[ObjectNode]:
        """
        Saves mbtiles file

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/ObjectNode'}}}

        """
        response = await self.__client.post(
            path='/map/upload',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=ObjectNode(**response.json()),
            response=response
        )
