from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Provisioning:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def get_provisioning_configs(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve all provisioning configurations

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/ProvisioningConfigObjectObject'}}}}

        """
        response = await self.__client.get(
            path='/provisioning',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def create_provisioning_config(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Create a provisioning configuration

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'integer', 'format': 'int64'}}}

        """
        response = await self.__client.post(
            path='/provisioning',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def update_provisioning_config(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update a provisioning configuration

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/provisioning/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def delete_provisioning_config(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Delete a provisioning configuration

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.delete(
            path=f'/provisioning/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )
