from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Realm:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def get_all_realms(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve all realms

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Realm'}}}}

        """
        response = await self.__client.get(
            path='/realm',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def create_realm(self, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Create a new realm

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.post(
            path='/realm',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def get_realm(self, name = str, headers: HeaderTypes | None = None) -> ResponseModel[Realm]:
        """
        Retrieve details about the currently authenticated and active realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/Realm'}}}

        """
        response = await self.__client.get(
            path=f'/realm/{name}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Realm(**response.json()),
            response=response
        )

    async def update_realm(self, name = str, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Update a realm

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.put(
            path=f'/realm/{name}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def delete_realm(self, name = str, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Delete a realm

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.delete(
            path=f'/realm/{name}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def get_accessible_realms(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve accessible realms for the authenticated user

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Realm'}}}}

        """
        response = await self.__client.get(
            path='/realm/accessible',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )
