from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Rule:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def create_asset_ruleset(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Create an asset ruleset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'integer', 'format': 'int64'}}}

        """
        response = await self.__client.post(
            path='/rules/asset',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_global_rulesets(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
         Retrieve the global rules

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/GlobalRuleset'}}}}

        """
        response = await self.__client.get(
            path='/rules',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def create_global_ruleset(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Create a global ruleset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'integer', 'format': 'int64'}}}

        """
        response = await self.__client.post(
            path='/rules',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def create_realm_ruleset(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Create a realm ruleset

        Possible responses:

          200 - default response
          {'*/*': {'schema': {'type': 'integer', 'format': 'int64'}}}

        """
        response = await self.__client.post(
            path='/rules/realm',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_asset_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[AssetRuleset]:
        """
        Retrieve an asset ruleset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/AssetRuleset'}}}

        """
        response = await self.__client.get(
            path=f'/rules/asset/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=AssetRuleset(**response.json()),
            response=response
        )

    async def update_asset_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update an asset ruleset

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/rules/asset/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def delete_asset_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Delete an asset ruleset

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.delete(
            path=f'/rules/asset/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def get_global_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[GlobalRuleset]:
        """
        Retrieve a global ruleset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/GlobalRuleset'}}}

        """
        response = await self.__client.get(
            path=f'/rules/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=GlobalRuleset(**response.json()),
            response=response
        )

    async def update_global_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update a global ruleset

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/rules/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def delete_global_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Delete a global ruleset

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.delete(
            path=f'/rules/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_realm_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[RealmRuleset]:
        """
        Retrieve a realm ruleset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/RealmRuleset'}}}

        """
        response = await self.__client.get(
            path=f'/rules/realm/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=RealmRuleset(**response.json()),
            response=response
        )

    async def update_realm_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update a realm ruleset

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/rules/realm/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def delete_realm_ruleset(self, id = int, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Delete a realm ruleset

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.delete(
            path=f'/rules/realm/{id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_asset_engine_info(self, asset_id = str, headers: HeaderTypes | None = None) -> ResponseModel[RulesEngineInfo]:
        """
        Retrieve information about an asset rules engine

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/RulesEngineInfo'}}}

        """
        response = await self.__client.get(
            path=f'/rules/info/asset/{asset_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=RulesEngineInfo(**response.json()),
            response=response
        )

    async def get_asset_geofences(self, asset_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Get the geofences of an asset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/GeofenceDefinition'}}}}

        """
        response = await self.__client.get(
            path=f'/rules/geofences/{asset_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def get_asset_rulesets(self, asset_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve the rules of an asset

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/AssetRuleset'}}}}

        """
        response = await self.__client.get(
            path=f'/rules/asset/for/{asset_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def get_global_engine_info(self, headers: HeaderTypes | None = None) -> ResponseModel[RulesEngineInfo]:
        """
        Retrieve information about the global rules engine

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/RulesEngineInfo'}}}

        """
        response = await self.__client.get(
            path='/rules/info/global',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=RulesEngineInfo(**response.json()),
            response=response
        )

    async def get_realm_engine_info(self, realm = str, headers: HeaderTypes | None = None) -> ResponseModel[RulesEngineInfo]:
        """
        Retrieve information about a realm rules engine

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/RulesEngineInfo'}}}

        """
        response = await self.__client.get(
            path=f'/rules/info/realm/{realm}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=RulesEngineInfo(**response.json()),
            response=response
        )

    async def get_realm_rulesets(self, realm = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve the rules of a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/RealmRuleset'}}}}

        """
        response = await self.__client.get(
            path=f'/rules/realm/for/{realm}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )
