from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class Syslog:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def get_events(self, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Retrieve the syslog events

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.get(
            path='/syslog/event',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def clear_events(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Clear the syslog events

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.delete(
            path='/syslog/event',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_config(self, headers: HeaderTypes | None = None) -> ResponseModel[SyslogConfig]:
        """
        Retrieve the syslog configuration

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/SyslogConfig'}}}

        """
        response = await self.__client.get(
            path='/syslog/config',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=SyslogConfig(**response.json()),
            response=response
        )

    async def update_config(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update the syslog configuration

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path='/syslog/config',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )
