from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class UiApps:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def get_app_infos(self, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Retrieve the info of the available applications

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.get(
            path='/apps/info',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def get_apps(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve a list of the available applications

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'type': 'string'}}}}

        """
        response = await self.__client.get(
            path='/apps',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def get_console_config(self, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Retrieve the console configuration

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.get(
            path='/apps/console_config',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )
