from httpx import Response

from ..http import HttpClient
from ..response import ResponseModel
from httpx._types import QueryParamTypes, HeaderTypes, CookieTypes, AuthTypes, TimeoutTypes, RequestExtensions,     RequestContent, RequestData, RequestFiles

################################################################
# This file is auto-generated by the openapi_generator script. #
################################################################


class User:
    __client: HttpClient

    def __init__(self, client: HttpClient):
        self.__client = client

    async def update_user(self, realm = str, headers: HeaderTypes | None = None) -> ResponseModel[User]:
        """
        Update a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/User'}}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/users',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=User(**response.json()),
            response=response
        )

    async def create_user(self, realm = str, headers: HeaderTypes | None = None) -> ResponseModel[User]:
        """
        Create a new user in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/User'}}}

        """
        response = await self.__client.post(
            path=f'/user/{realm}/users',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=User(**response.json()),
            response=response
        )

    async def delete_user(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Delete a user from a realm

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.delete(
            path=f'/user/{realm}/users/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def disconnect_user_session(self, realm = str, session_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Disconnect a user session using a session ID

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/disconnect/{session_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_user(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[User]:
        """
        Retrieve a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/User'}}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=User(**response.json()),
            response=response
        )

    async def get_client_roles(self, realm = str, client_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve client roles for a realm and client

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/Role'}}}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/{client_id}/roles',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def update_client_roles(self, realm = str, client_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update client roles for a realm and client

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/{client_id}/roles',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_current_user(self, headers: HeaderTypes | None = None) -> ResponseModel[User]:
        """
        Retrieve the currently authenticated user

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/User'}}}

        """
        response = await self.__client.get(
            path='/user/user',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=User(**response.json()),
            response=response
        )

    async def get_current_user_client_roles(self, client_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve client roles for the currently authenticated user using a client ID

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'type': 'string'}}}}

        """
        response = await self.__client.get(
            path=f'/user/user_roles/{client_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def get_current_user_realm_roles(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve realm roles for the currently authenticated user

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'type': 'string'}}}}

        """
        response = await self.__client.get(
            path='/user/user_realm_roles',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def get_user_client_roles(self, realm = str, user_id = str, client_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve client roles for a user using a client ID in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'type': 'string'}}}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/user_roles/{user_id}/{client_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def update_user_client_roles(self, realm = str, user_id = str, client_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update client roles for a user in a realm using a client ID

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/user_roles/{user_id}/{client_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_user_realm_roles(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve realm roles for a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'type': 'string'}}}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/user_realm_roles/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def update_user_realm_roles(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update realm roles for a user in a realm

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/user_realm_roles/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def get_user_sessions(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Retrieve sessions for a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/UserSession'}}}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/user_sessions/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def query_users(self, headers: HeaderTypes | None = None) -> ResponseModel[list]:
        """
        Query users based on criteria

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'array', 'items': {'$ref': '#/components/schemas/User'}}}}

        """
        response = await self.__client.post(
            path='/user/query',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=list(**response.json()),
            response=response
        )

    async def request_user_password_reset(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Request a password reset for a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/request-password-reset/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def request_password_reset(self, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Request a password reset for the currently authenticated user

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.put(
            path='/user/request-password-reset',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def reset_secret(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Reset the secret for a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'type': 'string'}}}

        """
        response = await self.__client.get(
            path=f'/user/{realm}/reset-secret/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def update_self(self, headers: HeaderTypes | None = None) -> ResponseModel[User]:
        """
        Update the currently authenticated user

        Possible responses:

          200 - default response
          {'application/json': {'schema': {'$ref': '#/components/schemas/User'}}}

        """
        response = await self.__client.put(
            path='/user/update',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=User(**response.json()),
            response=response
        )

    async def update_current_user_locale(self, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update locale for the current user in a realm

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path='/user/locale',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )

    async def update_password(self, realm = str, user_id = str, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Update the password for a user in a realm

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/reset-password/{user_id}',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def update_own_password(self, headers: HeaderTypes | None = None) -> ResponseModel[None]:
        """
        Update the password for the currently authenticated user

        Possible responses:

          200 - default response
          {'application/json': {}}

        """
        response = await self.__client.put(
            path='/user/reset-password',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=None(**response.json()),
            response=response
        )

    async def update_roles(self, realm = str, headers: HeaderTypes | None = None) -> ResponseModel[Any]:
        """
        Update roles for a realm

        Possible responses:

          200 - default response
          {'*/*': {}}

        """
        response = await self.__client.put(
            path=f'/user/{realm}/roles',
            headers=headers
        )

        response.raise_for_status()

        return ResponseModel(
            status_code=response.status_code,
            content=Any(**response.json()),
            response=response
        )
